apiVersion: v1
kind: Service
metadata:
  name: neo4j-api-service
  namespace: cjarcau
spec:
  selector:
    app: neo4j-api
  ports:
    - name: api
      protocol: TCP
      port: 49150
      targetPort: api
  type: ClusterIP
  clusterIP: 10.43.195.157