apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-api-deployment
  namespace: cjarcau
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
    spec:
      containers:
      - name: models
        image: scr4pp/models-api
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: host
        - name: POSTGRES_PORT
          value: "49140"
        - name: POSTGRES_DB
          value: postgres
        - name: MLFLOW_TRACKING_USERNAME
          value: admin
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: models-secret
              key: mlflow_password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws_secret_access_key
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: mlflow_s3_endpoint_url
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: mlflow_tracking_uri
        - name: KEYCLOAK_URL
          value: 
        imagePullPolicy: IfNotPresent