apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-api-deployment
  namespace: cjarcau
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
    spec:
      containers:
      - name: models
        image: scr4pp/models-api:arm28
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: POSTGRES_HOST
          value: 192.168.1.2
        - name: POSTGRES_PORT
          value: "32102"
        - name: POSTGRES_DB
          value: postgres
        - name: MLFLOW_TRACKING_USERNAME
          value: admin
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: models-secret
              key: mlflow_password
        - name: AWS_ACCESS_KEY_ID
          value: super
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: models-secret
              key: secret_key
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://62.72.21.79:9000
        - name: MLFLOW_TRACKING_URI
          value: http://192.168.1.2:31100
        - name: KEYCLOAK_URL
          value: https://keycloak.sedimark.work/auth/realms/react-keycloak/protocol/openid-connect/userinfo
        imagePullPolicy: IfNotPresent