apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cjarcau
  name: cronjob-manager-role
rules:
- apiGroups: ["apps"]  # For deployments
  resources: ["deployments"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]  # For services and secrets
  resources: ["services", "secrets"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "delete"]
