apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cjarcau
  name: main-api-role
rules:
- apiGroups: ["apps"]  # For deployments
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]  # For services and secrets
  resources: ["services", "secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete"]
