apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-manager-api-deployment
  namespace: cjarcau
  labels:
    app: notebook-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-manager-api
  template:
    metadata:
      labels:
        app: notebook-manager-api
    spec:
      serviceAccountName: notebook-manager-api-service-account
      containers:
      - name: notebook-manager-api
        image: scr4pp/kubernetes-api:arm33
        ports:
        - name: api
          containerPort: 8000
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: POSTGRES_HOST
          value: 192.168.1.2
        - name: POSTGRES_PORT
          value: "32102"
        - name: POSTGRES_DB
          value: postgres
        - name: NAMESPACE
          value: cjarcau
        - name: KEYCLOAK_URL
          value: https://keycloak.sedimark.work/auth/realms/react-keycloak/protocol/openid-connect/userinfo
        imagePullPolicy: IfNotPresent