apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: 
spec:
  selector:
    app: keycloak
  ports:
    - name: keycloak-port
      protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: keycloak-port
    - name: keycloak-http-port
      protocol: TCP
      port: 8442
      nodePort: 30442
      targetPort: keycloak-http-port
  type: LoadBalancer