apiVersion: v1
kind: Service
metadata:
  name: api-deleter-service
  namespace: cjarcau
spec:
  selector:
    app: api-deleter
  ports:
    - protocol: TCP
      port: 49153
      targetPort: 8000
  type: ClusterIP