apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-api-deployment
  namespace: cjarcau
  labels:
    app: neo4j-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-api
  template:
    metadata:
      labels:
        app: neo4j-api
    spec:
      containers:
      - name: neo4j-api
        image: scr4pp/neo4j-api:arm23
        env:
        - name: USERNAME
          value: 
        - name: PASS
          value: 
        - name: URI
          value:
        - name: INSIDE_DOCKER
          value: "true"
        - name: KEYCLOAK_URL
          value: 
        - name: PASSWORD
          value: 7dfe20e1136346b9dc5254f8e1941f97224a8bb50bb4b28d6acc3932a98600ec
        ports:
        - name: api
          containerPort: 8000
        imagePullPolicy: IfNotPresent