apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
  namespace: cjarcau
type: Opaque
data:
  password: c3VwZXJfZG9vcGVyX3NlY3JldAo=
  username: cG9zdGdyZXMK
  database: cG9zdGdyZXMK
  host: