apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cjarcau
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    nodePort: 32102
  selector:
    app: postgres