apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: 
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 49140
    targetPort: 5432
  selector:
    app: postgres