apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: main-api-rolebinding
  namespace: cjarcau
subjects:
- kind: ServiceAccount
  name: main-api-service-account
  namespace: cjarcau
roleRef:
  kind: Role
  name: main-api-role
  apiGroup: rbac.authorization.k8s.io
