apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deleter-rolebinding
  namespace: cjarcau
subjects:
- kind: ServiceAccount
  name: pod-deleter-service-account
  namespace: cjarcau
roleRef:
  kind: Role
  name: pod-deleter-role
  apiGroup: rbac.authorization.k8s.io
